server:
    port: 9000
spring:
  application:
    name: demo
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: pass
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
